import { computeSetupProgress } from '../setupProgress';
import { DEFAULT_CONFIG } from '@/lib/constants/configDefaults';
import { Configuracao } from '@/lib/types/database';

function baseConfig(overrides: Partial<Configuracao> = {}): Configuracao {
  return {
    id: 1,
    evento_id: 'evento-1',
    ...DEFAULT_CONFIG,
    ...overrides,
  } as Configuracao;
}

describe('computeSetupProgress', () => {
  it('marca tudo como pendente para uma configuração recém-criada (0%)', () => {
    const config = baseConfig({
      created_at: '2026-01-01T00:00:00.000Z',
      data_casamento: '2026-06-30', // 180 dias após created_at
    });

    const progress = computeSetupProgress(config, { agenda: 0, faq: 0, presentes: 0 });

    expect(progress.percent).toBe(0);
    expect(progress.items.every(i => !i.done)).toBe(true);
  });

  it('marca "nomes" como concluído quando ambos os nomes foram alterados', () => {
    const config = baseConfig({ noiva_nome: 'Layslla', noivo_nome: 'Marcus' });
    const progress = computeSetupProgress(config, { agenda: 0, faq: 0, presentes: 0 });
    const item = progress.items.find(i => i.key === 'nomes');
    expect(item?.done).toBe(true);
  });

  it('não marca "nomes" como concluído se só um dos dois foi alterado', () => {
    const config = baseConfig({ noiva_nome: 'Layslla', noivo_nome: DEFAULT_CONFIG.noivo_nome });
    const progress = computeSetupProgress(config, { agenda: 0, faq: 0, presentes: 0 });
    const item = progress.items.find(i => i.key === 'nomes');
    expect(item?.done).toBe(false);
  });

  it('trata a data como "ainda não definida" quando é ~180 dias após created_at (auto-gerada pelo eventService)', () => {
    const createdAt = new Date('2026-01-01T00:00:00.000Z');
    const autoGenerated = new Date(createdAt.getTime() + 180 * 24 * 60 * 60 * 1000);
    const config = baseConfig({
      created_at: createdAt.toISOString(),
      data_casamento: autoGenerated.toISOString().split('T')[0],
    });

    const progress = computeSetupProgress(config, { agenda: 0, faq: 0, presentes: 0 });
    expect(progress.items.find(i => i.key === 'data')?.done).toBe(false);
  });

  it('trata a data como definida quando o organizador escolheu uma data real diferente do auto-gerado', () => {
    const config = baseConfig({
      created_at: '2026-01-01T00:00:00.000Z',
      data_casamento: '2027-03-20',
    });

    const progress = computeSetupProgress(config, { agenda: 0, faq: 0, presentes: 0 });
    expect(progress.items.find(i => i.key === 'data')?.done).toBe(true);
  });

  it('marca "local" como concluído quando local e endereço foram alterados', () => {
    const config = baseConfig({ local_cerimonia: 'Sítio Catarina', endereco_cerimonia: 'Av. Governador Leonel de Moura' });
    const progress = computeSetupProgress(config, { agenda: 0, faq: 0, presentes: 0 });
    expect(progress.items.find(i => i.key === 'local')?.done).toBe(true);
  });

  it('usa a contagem de agenda/faq pra marcar os respectivos itens', () => {
    const config = baseConfig();
    const progress = computeSetupProgress(config, { agenda: 2, faq: 1, presentes: 0 });
    expect(progress.items.find(i => i.key === 'horarios')?.done).toBe(true);
    expect(progress.items.find(i => i.key === 'faq')?.done).toBe(true);
  });

  it('marca "horarios" como concluído quando cerimônia e recepção foram alteradas, mesmo sem nenhum item na agenda detalhada', () => {
    const config = baseConfig({ horario_cerimonia: '15:00', horario_recepcao: '20:00' });
    const progress = computeSetupProgress(config, { agenda: 0, faq: 0, presentes: 0 });
    expect(progress.items.find(i => i.key === 'horarios')?.done).toBe(true);
  });

  it('não marca "horarios" como concluído se só um dos dois horários foi alterado e não há item na agenda detalhada', () => {
    const config = baseConfig({ horario_cerimonia: '15:00', horario_recepcao: DEFAULT_CONFIG.horario_recepcao });
    const progress = computeSetupProgress(config, { agenda: 0, faq: 0, presentes: 0 });
    expect(progress.items.find(i => i.key === 'horarios')?.done).toBe(false);
  });

  it('contribuição: modo "nenhum" conta como resolvido sem precisar de PIX ou presentes', () => {
    const config = baseConfig({ modo_arrecadacao: 'nenhum' });
    const progress = computeSetupProgress(config, { agenda: 0, faq: 0, presentes: 0 });
    expect(progress.items.find(i => i.key === 'contribuicao')?.done).toBe(true);
  });

  it('contribuição: modo "gravata" exige pix_chave preenchida', () => {
    const semPix = baseConfig({ modo_arrecadacao: 'gravata', pix_chave: '' });
    expect(computeSetupProgress(semPix, { agenda: 0, faq: 0, presentes: 0 }).items.find(i => i.key === 'contribuicao')?.done).toBe(false);

    const comPix = baseConfig({ modo_arrecadacao: 'gravata', pix_chave: 'chave@pix.com' });
    expect(computeSetupProgress(comPix, { agenda: 0, faq: 0, presentes: 0 }).items.find(i => i.key === 'contribuicao')?.done).toBe(true);
  });

  it('contribuição: modo "presentes" exige ao menos 1 presente cadastrado', () => {
    const config = baseConfig({ modo_arrecadacao: 'presentes' });
    expect(computeSetupProgress(config, { agenda: 0, faq: 0, presentes: 0 }).items.find(i => i.key === 'contribuicao')?.done).toBe(false);
    expect(computeSetupProgress(config, { agenda: 0, faq: 0, presentes: 3 }).items.find(i => i.key === 'contribuicao')?.done).toBe(true);
  });

  it('calcula o percentual como a razão de itens concluídos', () => {
    const config = baseConfig({
      noiva_nome: 'Layslla',
      noivo_nome: 'Marcus',
      created_at: '2026-01-01T00:00:00.000Z',
      data_casamento: '2027-03-20',
    });
    // 2 de 7 itens concluídos (nomes + data)
    const progress = computeSetupProgress(config, { agenda: 0, faq: 0, presentes: 0 });
    expect(progress.completedCount).toBe(2);
    expect(progress.totalCount).toBe(7);
    expect(progress.percent).toBe(Math.round((2 / 7) * 100));
  });

  it('retorna 100% quando todos os itens estão concluídos', () => {
    const config = baseConfig({
      noiva_nome: 'Layslla',
      noivo_nome: 'Marcus',
      created_at: '2026-01-01T00:00:00.000Z',
      data_casamento: '2027-03-20',
      local_cerimonia: 'Sítio Catarina',
      endereco_cerimonia: 'Av. Governador Leonel de Moura',
      hero_images: ['https://res.cloudinary.com/x/foto.jpg'],
      modo_arrecadacao: 'nenhum',
    });
    const progress = computeSetupProgress(config, { agenda: 1, faq: 1, presentes: 0 });
    expect(progress.percent).toBe(100);
  });

  it('sempre retorna as 5 sugestões, independente do progresso', () => {
    const progress = computeSetupProgress(baseConfig(), { agenda: 0, faq: 0, presentes: 0 });
    expect(progress.suggestions).toHaveLength(5);
    expect(progress.suggestions.map(s => s.key)).toEqual(['cartao', 'fonte', 'animacao', 'link-unico', 'agenda-detalhada']);
  });

  it('sugestão "agenda-detalhada" linka pra /admin/agenda (página própria da tabela eventos_agenda), não pra uma âncora em Configurações', () => {
    // Bug real: a seção "Logística & Agenda" de /admin/configuracoes só
    // edita horario_cerimonia/horario_recepcao/local_cerimonia (campos
    // únicos), não deixa adicionar itens à tabela eventos_agenda — isso é
    // feito só em /admin/agenda. Cerimônia+recepção já bastam pro item
    // obrigatório 'horarios'; detalhar mais marcos é só sugestão opcional.
    const progress = computeSetupProgress(baseConfig(), { agenda: 0, faq: 0, presentes: 0 });
    const suggestion = progress.suggestions.find(s => s.key === 'agenda-detalhada');
    expect(suggestion?.anchor).toBe('/admin/agenda');
  });
});
