import { Configuracao } from '@/lib/types/database';
import { DEFAULT_CONFIG, AUTO_GENERATED_WEDDING_DATE_OFFSET_DAYS } from '@/lib/constants/configDefaults';

/**
 * Checklist de Setup Guiado (STORY-061).
 *
 * Substitui o banner estático + o wizard pós-login (que nunca persistia
 * nada — ver OnboardingWizard.tsx removido). Em vez de uma flag booleana
 * única (`eventos.onboarding_completed`), o progresso é 100% derivado dos
 * dados que já existem em `configuracoes`/`eventos_agenda`/`faq`/`presentes`
 * — não existe nenhuma tabela nova de estado, pra não duplicar fonte de
 * verdade (se o organizador apagar o único item de FAQ depois de marcado
 * como "completo", o cálculo se autocorrige sozinho).
 */

export interface SetupChecklistItem {
  key: string;
  label: string;
  done: boolean;
  /**
   * Pra onde o item linka: '#id' vira uma âncora dentro de
   * /admin/configuracoes; qualquer valor começando com '/' é usado como
   * path completo (ex: '/admin/agenda' — a tabela `eventos_agenda`, com
   * múltiplos itens de cerimônia/recepção/festa, é gerenciada numa página
   * própria, não dentro de Configurações).
   */
  anchor: string;
}

/** Cards de sugestão sempre visíveis — não entram na %, porque têm default
 * não-nulo (card_template, animacao_tipo, fontes) e não dá pra saber se foi
 * escolha consciente do organizador ou só o valor herdado. */
export interface SetupSuggestion {
  key: string;
  label: string;
  anchor: string;
}

export interface SetupProgress {
  items: SetupChecklistItem[];
  suggestions: SetupSuggestion[];
  completedCount: number;
  totalCount: number;
  /** 0-100, arredondado. */
  percent: number;
}

export interface SetupProgressCounts {
  agenda: number;
  faq: number;
  presentes: number;
}

/**
 * A data do casamento não tem um sentinel fixo confiável: quando o
 * organizador cria um evento pelo Dashboard (sem passar por /criar),
 * eventService.createEvent grava automaticamente `hoje + 180 dias` — uma
 * data "real" que muda a cada evento criado, não uma constante fixa. Por
 * isso comparamos contra `configuracoes.created_at + 180 dias` (com 1 dia
 * de tolerância) em vez de contra uma string fixa.
 */
function isWeddingDateStillAutoGenerated(config: Configuracao): boolean {
  if (!config.data_casamento) return true;

  if (!config.created_at) {
    // Sem created_at pra comparar (não deveria acontecer em produção) —
    // cai no sentinel estático do formulário como último recurso.
    return config.data_casamento === DEFAULT_CONFIG.data_casamento;
  }

  const createdAt = new Date(config.created_at).getTime();
  const weddingDate = new Date(config.data_casamento).getTime();
  if (Number.isNaN(createdAt) || Number.isNaN(weddingDate)) return true;

  const autoGeneratedDate = createdAt + AUTO_GENERATED_WEDDING_DATE_OFFSET_DAYS * 24 * 60 * 60 * 1000;
  const toleranceMs = 24 * 60 * 60 * 1000;
  return Math.abs(weddingDate - autoGeneratedDate) < toleranceMs;
}

function isNamesUnset(config: Configuracao): boolean {
  // "Feito" só quando os DOIS nomes foram alterados — um só já não conta.
  return config.noiva_nome === DEFAULT_CONFIG.noiva_nome || config.noivo_nome === DEFAULT_CONFIG.noivo_nome;
}

function isLocationUnset(config: Configuracao): boolean {
  // "Feito" só quando local E endereço foram alterados.
  return (
    (config.local_cerimonia || '') === DEFAULT_CONFIG.local_cerimonia ||
    (config.endereco_cerimonia || '') === DEFAULT_CONFIG.endereco_cerimonia
  );
}

function isContribuicaoUnset(config: Configuracao, presentesCount: number): boolean {
  if (config.modo_arrecadacao === 'nenhum') return false; // escolha explícita, conta como resolvido
  if (config.modo_arrecadacao === 'gravata') return !config.pix_chave;
  // 'presentes' (ou não definido): precisa de pelo menos 1 item na lista
  return presentesCount === 0;
}

export function computeSetupProgress(config: Configuracao, counts: SetupProgressCounts): SetupProgress {
  const items: SetupChecklistItem[] = [
    {
      key: 'nomes',
      label: 'Definir os nomes dos noivos',
      done: !isNamesUnset(config),
      anchor: '#noivos',
    },
    {
      key: 'data',
      label: 'Confirmar a data do casamento',
      done: !isWeddingDateStillAutoGenerated(config),
      anchor: '#agenda',
    },
    {
      key: 'local',
      label: 'Informar o local da cerimônia',
      done: !isLocationUnset(config),
      anchor: '#agenda',
    },
    {
      key: 'agenda-item',
      label: 'Adicionar pelo menos um item na agenda do dia',
      done: counts.agenda > 0,
      // Página própria (não é uma âncora em Configurações) — é onde a
      // tabela `eventos_agenda` é de fato gerenciada.
      anchor: '/admin/agenda',
    },
    {
      key: 'capa',
      label: 'Adicionar foto(s) de capa do convite',
      done: (config.hero_images?.length || 0) > 0,
      anchor: '#identidade-visual',
    },
    {
      key: 'contribuicao',
      label: 'Configurar como os convidados vão contribuir (PIX ou lista de presentes)',
      done: !isContribuicaoUnset(config, counts.presentes),
      anchor: '#contribuicao',
    },
    {
      key: 'faq',
      label: 'Adicionar pelo menos uma Pergunta Frequente',
      done: counts.faq > 0,
      anchor: '#faq',
    },
  ];

  const suggestions: SetupSuggestion[] = [
    { key: 'cartao', label: 'Escolher o modelo do cartão de compartilhamento (7 disponíveis)', anchor: '#cartao' },
    { key: 'fonte', label: 'Personalizar a tipografia premium do convite', anchor: '#identidade-visual' },
    { key: 'animacao', label: 'Escolher a animação de entrada (envelope, cinematográfica...)', anchor: '#animacao' },
    { key: 'link-unico', label: 'Revisar como os convidados vão se cadastrar (individual ou Link Único)', anchor: '#link-unico' },
  ];

  const completedCount = items.filter(i => i.done).length;
  const totalCount = items.length;
  const percent = totalCount === 0 ? 100 : Math.round((completedCount / totalCount) * 100);

  return { items, suggestions, completedCount, totalCount, percent };
}
