-- Migration: Finalize Multi-Tenant RLS and Data Isolation
-- Objetivo: Garantir isolamento total entre eventos (SaaS ready) usando evento_id.

-- 1. Limpar políticas legadas para evitar conflitos
DO $$
DECLARE
    pol record;
BEGIN
    FOR pol IN 
        SELECT policyname, tablename 
        FROM pg_policies 
        WHERE schemaname = 'public' 
        AND tablename IN ('eventos', 'configuracoes', 'convites', 'presentes', 'faq', 'evento_organizadores')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I', pol.policyname, pol.tablename);
    END LOOP;
END $$;

-- 2. POLÍTICAS PARA EVENTOS
ALTER TABLE eventos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Eventos: Visibilidade Master/Organizador" ON eventos
    FOR SELECT USING (
        EXISTS (SELECT 1 FROM public.perfis WHERE id = auth.uid() AND is_master = true)
        OR
        EXISTS (SELECT 1 FROM evento_organizadores WHERE evento_id = eventos.id AND user_id = auth.uid())
    );

CREATE POLICY "Eventos: Gestão Master/Owner" ON eventos
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.perfis WHERE id = auth.uid() AND is_master = true)
        OR
        EXISTS (SELECT 1 FROM evento_organizadores WHERE evento_id = eventos.id AND user_id = auth.uid() AND role = 'owner')
    );

-- 3. POLÍTICAS PARA CONFIGURACOES
ALTER TABLE configuracoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Config: Leitura Pública" ON configuracoes
    FOR SELECT USING (true); -- Convidados leem via slug na aplicação

CREATE POLICY "Config: Gestão Master/Owner" ON configuracoes
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.perfis WHERE id = auth.uid() AND is_master = true)
        OR
        EXISTS (SELECT 1 FROM evento_organizadores WHERE evento_id = configuracoes.evento_id AND user_id = auth.uid() AND role = 'owner')
    );

-- 4. POLÍTICAS PARA CONVITES
ALTER TABLE convites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Convites: Leitura Pública" ON convites
    FOR SELECT USING (true); -- Necessário para RSVP via slug/token

CREATE POLICY "Convites: Gestão Master/Organizador" ON convites
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.perfis WHERE id = auth.uid() AND is_master = true)
        OR
        EXISTS (SELECT 1 FROM evento_organizadores WHERE evento_id = convites.evento_id AND user_id = auth.uid())
    );

-- 5. POLÍTICAS PARA PRESENTES
ALTER TABLE presentes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Presentes: Leitura Pública" ON presentes
    FOR SELECT USING (true);

CREATE POLICY "Presentes: Gestão Master/Organizador" ON presentes
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.perfis WHERE id = auth.uid() AND is_master = true)
        OR
        EXISTS (SELECT 1 FROM evento_organizadores WHERE evento_id = presentes.evento_id AND user_id = auth.uid())
    );

-- 6. POLÍTICAS PARA FAQ
ALTER TABLE faq ENABLE ROW LEVEL SECURITY;

CREATE POLICY "FAQ: Leitura Pública" ON faq
    FOR SELECT USING (true);

CREATE POLICY "FAQ: Gestão Master/Organizador" ON faq
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.perfis WHERE id = auth.uid() AND is_master = true)
        OR
        EXISTS (SELECT 1 FROM evento_organizadores WHERE evento_id = faq.evento_id AND user_id = auth.uid())
    );

-- 7. Limpeza de restrições de Singleton em CONFIGURACOES (Garantia STORY-032)
ALTER TABLE configuracoes DROP CONSTRAINT IF EXISTS configuracoes_id_check;
ALTER TABLE configuracoes ALTER COLUMN id DROP DEFAULT;
-- O ID já deve ser auto-incremental via migration anterior, mas garantimos aqui
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'configuracoes' AND column_name = 'id' AND is_identity = 'YES') THEN
        ALTER TABLE configuracoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

NOTIFY pgrst, 'reload schema';
